### ISSUE TITLE
[BUG]: Unable to start lesson Error 4XX - 5XX

### ISSUE THREAD

**Issue by beksajt** [freeCodeCamp/solana-curriculum#20]
### Project
[solana-curriculum](https://github.com/freeCodeCamp/solana-curriculum)
### Lesson Number
1
### Issue/Experience
Unable to start lesson
### Code and Screenshots
After running "freeCodeCamp: Run Course" Page with lessons available is showing, but selecting first lesson causes error as below:

> Error 4XX - 5XX
> Client has disconnected from local server
> 
> To Keep Learning:
> First, try refresh this page
> Otherwise:
> Open the command palette
> Select the freeCodeCamp: Shutdown Course command
> Open the command palette
> Select the freeCodeCamp: Run Course command

Of course restarting course/reconnecting/re-initialising repo does not help.

Terminal output:

```
: No such file or directory
BashRC Sourced
root@4240d2562deb:/workspace/solana-curriculum# cd . && NODE_ENV=production node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-09-22 09:25:12 Listening on port 8080
🔵 INFO:  2022-09-22 09:25:15 Watching for file changes on /workspace/solana-curriculum
file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:58
  const description = lesson.match(
                             ^

TypeError: Cannot read properties of undefined (reading 'match')
    at getLessonDescription (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:58:30)
    at runLesson (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)
    at async FSWatcher.<anonymous> (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/hot-reload.js:47:7)

Node.js v18.9.0
root@4240d2562deb:/workspace/solana-curriculum# 
```

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

I am unable to reproduce. Would you mind sharing the output of:

```bash
cat config/state.json
```

And 

```bash
cat config/projects.json
```

**Comment by beksajt** [comment]
```
root@4240d2562deb:/workspace/solana-curriculum# cat config/state.json
{
  "currentProject": "learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract",
  "locale": "english"
}root@4240d2562deb:/workspace/solana-curriculum# cat config/projects.json
[
  {
    "id": 0,
    "title": "Learn How to Set Up Solana by Building a Hello World Smart Contract",
    "dashedName": "learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract",
    "isIntegrated": false,
    "description": "In this course, you will learn how to set up Solana by building a simple hello world contract.",
    "isPublic": true,
    "currentLesson": 1,
    "runTestsOnWatch": true,
    "numberOfLessons": 58
  },
  {
    "id": 1,
    "title": "More Coming Soon...",
    "dashedName": "build-x-using-y",
    "isIntegrated": true,
    "description": "",
    "isPublic": false,
    "currentLesson": 1,
    "numberOfLessons": 1
  }
]root@4240d2562deb:/workspace/solana-curriculum# 
```

**Comment by ShaunSHamilton** [comment]
Thank you. I do not see any issue there, and I cannot think what would be causing this just for you.

One last check:

```bash
head -n 26 curriculum/locales/english/learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract.md
```

**Comment by beksajt** [comment]
```
root@4240d2562deb:/workspace/solana-curriculum# head -n 26 curriculum/locales/english/learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract.md
# Solana - Learn How to Set Up Solana by Building a Hello World Smart Contract

## 1

### --description--

Welcome to the Solana curriculum! For the duration of this project, you will be working in the `learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract/` directory.

Open a new terminal, and change into the above directory.

_Note: Do not change the existing terminal_

### --tests--

You should use `cd` to change into the `learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract/` directory.

```js
const cwdFile = await __helpers.getCWD();
const cwd = cwdFile.split('\n').filter(Boolean).pop();
assert.include(
![repro](https://user-images.githubusercontent.com/28839918/191765722-42d969c6-cf44-4e95-a281-cd09f03778fb.gif)

  cwd,
  'learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract'
);
```

## 2
```

**Comment by beksajt** [comment]
That was the issue. Reversed all changes helped. Thank you!
