### ISSUE TITLE
[HELP]: can not run course

### ISSUE THREAD

**Issue by yadrena** [freeCodeCamp/solana-curriculum#347]
### Project
solana-curriculum
### Lesson Number
learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract
### Question
Can not run tests
### Code and Screenshots
Errors:
![2024-06-11 17 36 42](https://github.com/freeCodeCamp/solana-curriculum/assets/19557355/b1a4fb2a-ca41-4bf5-b1a0-3814717858af)
![2024-06-11 17 36 58](https://github.com/freeCodeCamp/solana-curriculum/assets/19557355/765a31dc-0b43-4993-b9ee-98e794b87e8d)

```
 ERROR:  2024-06-11 10:34:56 Test #1: Error: Could not find /workspace/solana-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:107:37), <anonymous>:1:31)
    at async file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:107:31
    at async Promise.allSettled (index 0)
    at async runTests (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:145:19)
    at async Object.handleRunTests [as run-tests] (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:68:3)
🔴 ERROR:  2024-06-11 10:35:05 Test #1: Error: Could not find /workspace/solana-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:107:37), <anonymous>:1:31)
    at async file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:107:31
    at async Promise.allSettled (index 0)
    at async runTests (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:145:19)
    at async Object.handleRunTests [as run-tests] (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:68:3)
🔴 ERROR:  2024-06-11 10:35:46 Test #1: Error: Could not find /workspace/solana-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:107:37), <anonymous>:1:31)
    at async file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:107:31
    at async Promise.allSettled (index 0)
    at async runTests (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:145:19)
    at async Object.handleRunTests [as run-tests] (file:///workspace/solana-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:68:3)
```

**Comment by ShaunSHamilton** [comment]
Hello there,

You should not have that many changes in your source control. Restore all the files, and restart the server.
